---
# Playbook: Proxmox ACLs Setup
# Description: Create the ACLs in proxmox
# Author: lb0o
# Last Updated: 2025

- name: Map GPUs in Proxmox Environment
  hosts: proxmox
  gather_facts: true
  roles:
    - role: ../roles/proxmox_acl
      vars:
        secrets_file: "{{ playbook_dir }}/../envs/.host_vars/.secretspve.yml"
        output_dir: "{{ playbook_dir }}/../envs/cozystack"
        proxmox_validate_certs: false
        user_real_id: "cozystack@pve"
        token_ids: 
          - "cozystack-admin"
          - "cozystack-readonly"
          - "cozystack-provisioner"
          - "cozystack-mapping-gpu"
        resource_id: "{{ lookup('pipe', 'date +%Y%m%d') }}"
        acl_roles:
          - id: "cozystack-admin"
            privs: "Datastore.Allocate,Datastore.AllocateSpace,VM.Allocate,VM.Audit,VM.Config.CDROM,VM.Config.CPU,VM.Config.Cloudinit,VM.Config.Disk,VM.Config.HWType,VM.Config.Memory,VM.Config.Network,VM.Config.Options,VM.PowerMgmt,VM.Migrate,VM.Monitor,VM.Snapshot,VM.Clone,Mapping.Audit,Mapping.Modify,Mapping.Use,Sys.Audit,Sys.Modify"
          - id: "cozystack-readonly"
            privs: "VM.Audit,VM.Monitor,Datastore.Audit,Mapping.Audit"
          - id: "cozystack-provisioner"
            privs: "Datastore.Allocate,VM.Allocate,VM.Config.CDROM,VM.Config.CPU,VM.Config.Cloudinit,VM.Config.Disk,VM.Config.HWType,VM.Config.Memory,VM.Config.Network,VM.Config.Options,VM.Migrate,VM.PowerMgmt,VM.Snapshot,Sys.Audit,Sys.Modify"
          - id: "cozystack-mapping-gpu"
            privs: "Sys.Modify,Sys.Audit,Mapping.Modify,Mapping.Use,Mapping.Audit"